name: dp100labs
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - joblib
  - matplotlib
  - mlflow
  - numpy
  - pandas
  - pip
  - scikit-learn
  - pip:
    - azureml-defaults
    - azureml-mlflow
    - azureml-sdk
    - azureml-widgets
